### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by abdurrahmanekr** [abdurrahmanekr/peanut#1]
- [x] Buffer.alloc is not a function
- [ ] User Authentication cookie
- [ ] Chat list add
- [ ] Single chat list add
- [ ] Group chat list add

**Comment by akshgods** [comment]
@abdurrahmanekr  hi, nice to llok at your library. just want to know.. it build successfully .
apk get installed. but after adding credential it does not connect to server . no error code or there is no error i get. on server i dint get user connected.


only one thing i got in console  :(

TypeError: Cannot read property 'random' of undefined
    at Object.randomBytes (E:\react\peanut\node_modules\react-native-randombytes\index.js:42)
    at E:\react\peanut\node_modules\sjcl\sjcl.js:50
    at loadModuleImplementation (E:\react\peanut\node_modules\metro\src\lib\polyfills\require.js:214)
    at guardedLoadModule (E:\react\peanut\node_modules\metro\src\lib\polyfills\require.js:148)
    at _require (E:\react\peanut\node_modules\metro\src\lib\polyfills\require.js:132)
    at E:\react\peanut\node_modules\react-native-randombytes\index.js:5
    at loadModuleImplementation (E:\react\peanut\node_modules\metro\src\lib\polyfills\require.js:214)
    at guardedLoadModule (E:\react\peanut\node_modules\metro\src\lib\polyfills\require.js:148)
    at _require (E:\react\peanut\node_modules\metro\src\lib\polyfills\require.js:132)
    at E:\react\peanut\node_modules\sasl-scram-sha-1\lib\utils.js:1

**Comment by abdurrahmanekr** [comment]
Hi, @akshgods. Have you changed the following codes?
https://github.com/abdurrahmanekr/peanut/blob/d1324e85704f3c6e11eee8492ef11b0b751b5fbc/index.js#L45-L51

**Comment by faysal515** [comment]
@akshgods try updating react native version to 0.56. I got the exact same error, updating rn version worked for me. Though I still get a crypto error but that doesn't block it from running the app

**Comment by akshgods** [comment]
thanks @faysal515  i tried for react native version to 0.56. , but i'm getting some android related issue on 0.56 version (not able to build on this version). once i resolve that.  i will late you know my update on issue. :)
